### ISSUE TITLE
Github Organization Name

### ISSUE THREAD

**Issue by rabernat** [altMITgcm/MITgcm#18]
Do you plan to keep `altMITgcm` as the github organization for these repos? Wouldn't `MITgcm` be better.

Who is maintaining this?
https://github.com/MITgcm

**Comment by christophernhill** [comment]
•Test setup is at
•
•https://github.com/altMITgcm/MITgcm
•Mostly follows pre-existing directory structure except documentation
is now within the same directory tree (and in a different format – see
later)
•
•Currently testing pull request (PR) workflows for both code and documentation
•4 people with github PR accept auth (Jean-Michel, Oliver, Chris, Ed)
•2 approvals required to merge
•Travis rudimentary automated testing
•HowTo guide here
http://mitgcm-example.readthedocs.io/en/latest/contributing/contributing.html
- work in progress, feedback/questions happily incorporated – please
send.
•
•Note - path names (github.com/altMITgcm/MITgcm and
mitgcm-example.readthedocs.io ) are intermediate. Things will
ultimately migrate to github.com/MITgcm/MITgcm and
mitgcm.readthedocs.io
